// Ranking de popularidade pra HQs ocidentais (Marvel, DC, Image, etc.) e
// quadrinhos em geral. Quanto MENOR o número, mais famoso. Match case-insensitive
// via `name.toLowerCase().includes(key)`.
const POPULARITY: Array<[string, number]> = [
  // Tier S — ícones globais
  ["spider-man", 1],
  ["spiderman", 1],
  ["homem-aranha", 1],
  ["homem aranha", 1],
  ["batman", 2],
  ["superman", 3],
  ["super-homem", 3],
  ["super homem", 3],
  ["wonder woman", 4],
  ["mulher maravilha", 4],
  ["mulher-maravilha", 4],
  ["x-men", 5],
  ["xmen", 5],
  ["wolverine", 6],
  ["hulk", 7],
  ["iron man", 8],
  ["homem de ferro", 8],
  ["homem-de-ferro", 8],
  ["thor", 9],
  ["captain america", 10],
  ["capitão américa", 10],
  ["capitao america", 10],
  ["avengers", 11],
  ["vingadores", 11],
  ["justice league", 12],
  ["liga da justiça", 12],
  ["liga da justica", 12],
  ["flash", 13],
  ["green lantern", 14],
  ["lanterna verde", 14],
  ["aquaman", 15],
  ["deadpool", 16],
  ["fantastic four", 17],
  ["quarteto fantástico", 17],
  ["quarteto fantastico", 17],
  ["daredevil", 18],
  ["demolidor", 18],
  ["punisher", 19],
  ["justiceiro", 19],
  // Tier A
  ["venom", 20],
  ["doctor strange", 21],
  ["doutor estranho", 21],
  ["black panther", 22],
  ["pantera negra", 22],
  ["ant-man", 23],
  ["homem-formiga", 23],
  ["guardians of the galaxy", 24],
  ["guardiões da galáxia", 24],
  ["guardioes da galaxia", 24],
  ["robin", 25],
  ["nightwing", 26],
  ["asa noturna", 26],
  ["catwoman", 27],
  ["mulher-gato", 27],
  ["mulher gato", 27],
  ["harley quinn", 28],
  ["joker", 29],
  ["coringa", 29],
  ["green arrow", 30],
  ["arqueiro verde", 30],
  ["supergirl", 31],
  ["batgirl", 32],
  ["teen titans", 33],
  ["jovens titãs", 33],
  ["jovens titas", 33],
  ["sandman", 34],
  ["watchmen", 35],
  ["v for vendetta", 36],
  ["v de vingança", 36],
  ["walking dead", 37],
  ["invincible", 38],
  ["invencível", 38],
  ["invencivel", 38],
  ["saga", 39],
  ["preacher", 40],
  ["hellboy", 41],
  ["spawn", 42],
  ["sin city", 43],
  ["kick-ass", 44],
  ["kick ass", 44],
  ["scott pilgrim", 45],
  ["ms. marvel", 46],
  ["ms marvel", 46],
  ["captain marvel", 47],
  ["capitã marvel", 47],
  ["capita marvel", 47],
  ["she-hulk", 48],
  ["mulher-hulk", 48],
  ["silver surfer", 49],
  ["surfista prateado", 49],
  // Tier B — clássicos / nicho
  ["new mutants", 50],
  ["novos mutantes", 50],
  ["x-force", 51],
  ["x force", 51],
  ["x-factor", 52],
  ["alpha flight", 53],
  ["tropa alfa", 53],
  ["inhumans", 54],
  ["inumanos", 54],
  ["eternals", 55],
  ["eternos", 55],
  ["moon knight", 56],
  ["cavaleiro da lua", 56],
  ["ghost rider", 57],
  ["motoqueiro fantasma", 57],
  ["nova", 58],
  ["shazam", 59],
  ["martian manhunter", 60],
  ["caçador de marte", 60],
  ["cacador de marte", 60],
  ["hawkman", 61],
  ["gavião negro", 61],
  ["gaviao negro", 61],
  ["legion of super-heroes", 62],
  ["legião dos super-heróis", 62],
  ["doom patrol", 63],
  ["patrulha do destino", 63],
  ["swamp thing", 64],
  ["monstro do pântano", 64],
  ["monstro do pantano", 64],
  ["constantine", 65],
  ["hellblazer", 65],
  ["lobo", 66],
  ["red hood", 67],
  ["capuz vermelho", 67],
  ["birds of prey", 68],
  ["aves de rapina", 68],
  ["suicide squad", 69],
  ["esquadrão suicida", 69],
  ["esquadrao suicida", 69],
  ["runaways", 70],
  ["fugitivos", 70],
  ["young avengers", 71],
  ["jovens vingadores", 71],
  ["squirrel girl", 72],
  ["garota esquilo", 72],
  ["thanos", 73],
  ["darkseid", 74],
  ["doomsday", 75],
  ["galactus", 76],
  ["magneto", 77],
  ["mystique", 78],
  ["sabretooth", 79],
  ["dentes-de-sabre", 79],
  ["tintin", 85],
  ["tintim", 85],
  ["asterix", 86],
  ["astérix", 86],
  ["mickey", 87],
  ["donald", 88],
  ["pato donald", 88],
  ["tio patinhas", 89],
  ["turma da mônica", 90],
  ["turma da monica", 90],
  ["mafalda", 91],
  ["calvin", 92],
  ["garfield", 93],
  ["peanuts", 94],
  ["snoopy", 94],
];

/** Score de popularidade ocidental (menor = mais famoso). Sem match → final da fila. */
export function comicsPopularityScore(name: string): number {
  const n = name.toLowerCase();
  let best = Number.MAX_SAFE_INTEGER;
  for (const [k, score] of POPULARITY) {
    if (n.includes(k) && score < best) best = score;
  }
  return best;
}
